# Generated by Django 5.1.4 on 2024-12-31 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='estado',
            table='ESTADOS',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='USUARIOS',
        ),
    ]
